sonar.projectKey=jellywatch-front
sonar.projectName=Jellywatch Front
sonar.sources=src
sonar.tests=src/test,cypress
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.cy.ts
sonar.exclusions=src/test/**,**/*.test.ts,**/*.test.tsx,node_modules/**,dist/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
